### ISSUE TITLE
Support nested yml format

### ISSUE THREAD

**Issue by khepin** [servergrove/TranslationEditorBundle#1]
If my files are formatted like this:

```
homepage:
    title: Welcome
    sidebar:
        title: Menu
        subtitle: Chose something to do

aboutpage:
    title: About us
    contact: Contact us
```

Then the bundle will import only 2 keys: `homepage` and `aboutpage` with values: `Array`. Either the import should flatten the file while importing them or it should recursively look for the values.
